name: PR Build
on:
  pull_request:
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        env:
          CDK_DEFAULT_ACCOUNT: 108929950724
          CDK_DEFAULT_REGION: us-east-1
        run: |
          cd cdk
          npm i
          npm run synth -- -q
      - name: Create Release
        run: |
          git fetch
          last_release=$(git describe --abbrev=0 --tags | sed -e 's/v//')

          last_major_version=$(echo $last_release | cut -d '.' -f 1)
          last_minor_version=$(echo $last_release | cut -d '.' -f 2)
          last_patch_version=$(echo $last_release | cut -d '.' -f 3)

          # this is stupid but I might want to build on it later
          new_major_version=$last_major_version
          new_minor_version=$last_minor_version
          new_patch_version=$((last_patch_version+1))

          new_release="v$new_major_version.$new_minor_version.$new_patch_version"

          echo "Last Release: $last_release"
          echo "New Release: $new_release"

          curl -Lv \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/jim-brighter/jimsweather.xyz/releases \
          -d '{
            "tag_name": "'"$new_release"'",
            "name": "'"$new_release"'",
            "generate_release_notes": true
          }'
